create table "kmsDatabase" (
    "id" integer generated by default as identity primary key,
    "createdAt" timestamp,
    "lastModifiedAt" timestamp,
    "firstName" varchar(255),
    "lastName" varchar(255),
    "age" integer,
    "city" varchar(255),
    "gender" varchar(1) CHECK ("gender" IN ('M', 'F'))
);
