create table kms_database (
    id integer generated by default as identity primary key,
    created_at timestamp,
    last_modified_at timestamp,
    first_name varchar(255),
    last_name varchar(255),
    age integer,
    city varchar(255),
    gender varchar(1) CHECK (gender IN ('M', 'F'))
);
